version: '3'

volumes:
  pg_data:
  static:


services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    build:
      context: longevity
      dockerfile: Dockerfile
    volumes:
      - static:/backend_static
    depends_on:
      - db
    env_file: .env

  nginx:
    image: nginx:1.19.3
    env_file: .env
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles/
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - 8000:80
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis
